# Generated by Django 5.2.13 on 2026-04-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kahoot", "0002_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="kahoot.category",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="score",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
